name: StrengthSMP
version: '${project.version}'
main: dijon.strengthsmp.StrengthSMP
api-version: '1.21'
commands:
  strength:
    usage: /strength
  attack:
    usage: /attack
  startevent:
    usage: /startevent
  tpstrength:
    usage: /tpstrength